version:  '3.7'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DB_PORT}:3306
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql:rw

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    container_name: nginx
    volumes:
      - ./core/public:/app/symfony:rw,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/uploadsize.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - .env
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: on-failure
    volumes:
      - ./core:/app/symfony:rw,cached
    env_file:
      - .env
    user: ${LOCAL_USER}
    depends_on:
      - db
      - redis

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/bitnami
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  redis:
    image: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 8181:80

volumes:
  db-data: # If we delete mysql image, the previous build db is not lost
  rabbitmq-data: