# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    filter_sets:
        thumb360x230:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        thumb100x64:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 64]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound