vich_uploader:
    db_driver: orm
    mappings:
        house_image:
            uri_prefix: /images/houses
            upload_destination: '%kernel.project_dir%/public/images/houses'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
